Watching for file changes with StatReloader
[08/Jul/2023 16:22:35] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:22:35] "GET /static/css/style.css HTTP/1.1" 200 2150
[08/Jul/2023 16:24:08] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:24:08] "GET /static/css/style.css HTTP/1.1" 200 2150
[08/Jul/2023 16:24:08] "GET /media/websrc/noti.png HTTP/1.1" 200 401
[08/Jul/2023 16:24:09] "GET /media/websrc/rest-1.png HTTP/1.1" 200 188122
[08/Jul/2023 16:24:09] "GET /media/websrc/home_active.png HTTP/1.1" 200 825
[08/Jul/2023 16:24:09] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 200 1018
[08/Jul/2023 16:24:09] "GET /static/font/SF-Pro.ttf HTTP/1.1" 200 6110460
[08/Jul/2023 16:24:09] "GET /media/websrc/search.png HTTP/1.1" 200 487
[08/Jul/2023 16:24:09] "GET /media/websrc/gift_deactive.png HTTP/1.1" 200 849
[08/Jul/2023 16:24:10] "GET /media/websrc/user_deactive.png HTTP/1.1" 200 915
[08/Jul/2023 16:26:17] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:26:18] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[08/Jul/2023 16:26:18] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[08/Jul/2023 16:26:18] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[08/Jul/2023 16:26:18] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[08/Jul/2023 16:26:18] "GET /static/css/style.css HTTP/1.1" 200 2150
[08/Jul/2023 16:26:26] "GET /media/websrc/search.png HTTP/1.1" 200 487
[08/Jul/2023 16:26:26] "GET /media/websrc/noti.png HTTP/1.1" 200 401
[08/Jul/2023 16:26:29] "GET /media/websrc/rest-1.png HTTP/1.1" 200 188122
[08/Jul/2023 16:26:29] "GET /media/websrc/home_active.png HTTP/1.1" 200 825
[08/Jul/2023 16:26:29] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 200 1018
[08/Jul/2023 16:26:31] "GET /media/websrc/gift_deactive.png HTTP/1.1" 200 849
[08/Jul/2023 16:26:32] "GET /media/websrc/user_deactive.png HTTP/1.1" 200 915
[08/Jul/2023 16:26:39] "GET /static/font/SF-Pro.ttf HTTP/1.1" 200 6110460
[08/Jul/2023 16:27:06] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:27:06] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:27:40] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/search.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[08/Jul/2023 16:27:40] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[08/Jul/2023 16:29:37] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:29:38] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:29:54] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:29:54] "GET /static/css/style.css HTTP/1.1" 200 2150
[08/Jul/2023 16:29:54] "GET /media/websrc/noti.png HTTP/1.1" 200 401
[08/Jul/2023 16:29:54] "GET /media/websrc/search.png HTTP/1.1" 200 487
[08/Jul/2023 16:29:54] "GET /media/websrc/home_active.png HTTP/1.1" 200 825
[08/Jul/2023 16:29:54] "GET /media/websrc/rest-1.png HTTP/1.1" 200 188122
[08/Jul/2023 16:29:54] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 200 1018
[08/Jul/2023 16:29:54] "GET /media/websrc/gift_deactive.png HTTP/1.1" 200 849
[08/Jul/2023 16:29:54] "GET /media/websrc/user_deactive.png HTTP/1.1" 200 915
[08/Jul/2023 16:29:55] "GET /static/font/SF-Pro.ttf HTTP/1.1" 200 6110460
[08/Jul/2023 16:32:48] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:32:48] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/search.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:32:48] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:33:59] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/search.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:33:59] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET / HTTP/1.1" 200 2233
[08/Jul/2023 16:53:50] "GET /static/css/style.css HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/search.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[08/Jul/2023 16:53:50] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 06:00:00] code 400, message Bad request version ('À(À$À\x14À')
[09/Jul/2023 06:00:00] You're accessing the development server over HTTPS, but it only supports HTTP.

[09/Jul/2023 13:03:54,708] - Broken pipe from ('167.94.145.57', 60298)

[09/Jul/2023 13:03:55] code 400, message Bad request version ('À\x14À')
[09/Jul/2023 13:03:55] You're accessing the development server over HTTPS, but it only supports HTTP.

[09/Jul/2023 13:03:56] "GET / HTTP/1.1" 200 2233
[09/Jul/2023 13:03:56,847] - Broken pipe from ('167.94.145.57', 60910)

[09/Jul/2023 13:03:57] "GET / HTTP/1.1" 200 2233
[09/Jul/2023 13:03:57] code 505, message Invalid HTTP version (2.0)
[09/Jul/2023 13:03:57] "PRI * HTTP/2.0" 505 -
Not Found: /favicon.ico
[09/Jul/2023 13:03:58] "GET /favicon.ico HTTP/1.1" 404 2665
[09/Jul/2023 14:07:14] "GET / HTTP/1.1" 200 2233
[09/Jul/2023 14:07:15] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/search.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /static/css/style.css HTTP/1.1" 304 0
[09/Jul/2023 14:07:15] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[09/Jul/2023 14:31:36] "GET / HTTP/1.1" 200 2233
[09/Jul/2023 14:31:37] "GET /static/css/style.css HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/noti.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/search.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/user_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/rest-1.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/home_active.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/restaurant_deactive.png HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /static/font/SF-Pro.ttf HTTP/1.1" 304 0
[09/Jul/2023 14:31:37] "GET /media/websrc/gift_deactive.png HTTP/1.1" 304 0
/home/dmsai2/Desktop/COARR/server/api/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2023 - 16:22:33
Django version 3.2.20, using settings 'project.settings'
Starting development server at http://117.16.136.174:9000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/dmsai2/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmsai2/Desktop/COARR/server/api/admin.py", line 2, in <module>
    from .models import Review, User
ImportError: cannot import name 'Review' from 'api.models' (/home/dmsai2/Desktop/COARR/server/api/models.py)

/home/dmsai2/Desktop/COARR/server/api/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/dmsai2/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmsai2/Desktop/COARR/server/api/admin.py", line 2, in <module>
    from .models import Review, User
ImportError: cannot import name 'Review' from 'api.models' (/home/dmsai2/Desktop/COARR/server/api/models.py)

/home/dmsai2/Desktop/COARR/server/api/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/dmsai2/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmsai2/Desktop/COARR/server/api/admin.py", line 2, in <module>
    from .models import Review, User
ImportError: cannot import name 'Review' from 'api.models' (/home/dmsai2/Desktop/COARR/server/api/models.py)

/home/dmsai2/Desktop/COARR/server/api/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/dmsai2/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/dmsai2/Desktop/COARR/server/venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/dmsai2/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmsai2/Desktop/COARR/server/api/admin.py", line 2, in <module>
    from .models import Review, User
ImportError: cannot import name 'Review' from 'api.models' (/home/dmsai2/Desktop/COARR/server/api/models.py)

/home/dmsai2/Desktop/COARR/server/api/admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
